import type { NeuronWebTheme } from './types';

export const DEFAULT_THEME: NeuronWebTheme = {
  colors: {
    background: '#020314',
    domainColors: {},
    defaultDomainColor: '#c0c5ff',
    edgeDefault: '#4d4d55',
    edgeActive: '#c6d4ff',
    edgeSelected: '#ffffff',
    labelText: '#ffffff',
    labelBackground: 'rgba(5, 6, 31, 0.8)',
  },
  typography: {
    labelFontFamily: 'system-ui, sans-serif',
    labelFontSize: 12,
    labelFontWeight: '500',
  },
  effects: {
    starfieldEnabled: true,
    starfieldColor: '#ffffff',
    glowEnabled: true,
    glowIntensity: 0.6,
    ambientMotionEnabled: true,
    ambientMotionSpeed: 0.6,
    ambientMotionAmplitude: 0.25,
    edgeFlowEnabled: true,
    edgeFlowSpeed: 1.2,
    autoRotateEnabled: false,
    autoRotateSpeed: 0.25,
    postprocessingEnabled: true,
    bloomEnabled: false,
    bloomStrength: 0.6,
    bloomRadius: 0.35,
    bloomThreshold: 0.2,
    vignetteEnabled: false,
    vignetteDarkness: 0.6,
    vignetteOffset: 0.25,
    colorGradeEnabled: false,
    colorGradeIntensity: 0.2,
    backgroundIntensity: 0.9,
    fogEnabled: true,
    fogColor: '#020314',
    fogNear: 24,
    fogFar: 160,
  },
  animation: {
    focusDuration: 800,
    transitionDuration: 650,
    easing: 'easeInOut',
    hoverScale: 1.12,
    selectedScale: 1.4,
    selectionPulseScale: 0.35,
    selectionPulseDuration: 520,
    hoverCardFadeDuration: 160,
    hoverCardSlideDistance: 6,
    enableCameraTween: true,
    enableHoverScale: true,
    enableSelectionPulse: true,
    enableSelectionRipple: true,
  },
};
